logLevel = "INFO"
checkNewVersion = false

[traefikLog]
  filePath = "/etc/traefik/traefik.log"
[accessLog]
  filePath = "/etc/traefik/access.log"

[api]
  dashboard = true
  debug = true
  recentErrors = 30

[respondingTimeouts]
  readTimeout = "20s"
  writeTimeout = "20s"
  idleTimeout = "60s"

[forwardingTimeouts]
  dialTimeout = "20s"
  responseHeaderTimeout = "20s"

defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
    address = ":80"
#  [entryPoints.https]
#    address = ":443"
#    [entryPoints.https.tls]
#    minVersion = "VersionTLS12"
#    [[entryPoints.https.tls.certificates]]
#      certFile = "/etc/traefik/myCertificate.cer"
#      keyFile = "/etc/traefik/myKey.key"

[docker]
  endpoint = "tcp://<host IP address>:2375"
  domain = "docker.localhost"
  watch = true
  swarmmode = true
  exposedByDefault = true